/*
 * Copyright (c) 2022 Christopher Hettrick <chris@structfoo.com>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#include <syscall.h>

#ifdef MACHINE_GBA
#include <machine/machparam.h>
#endif

#ifndef MACHINE_GBA

#define	ENTRY(x) \
	.text; \
	.align	2; \
	.thumb_func; \
	.globl	x; \
	.type	x, %function; \
x:

#define	END(x) \
	.size	x, . - x

#define	SYS(x) \
	ENTRY(x); \
	svc	#SYS_##x; \
	bcs	1f; \
	bx	lr; \
1:	ldr	r1, =errno; \
	str	r0, [r1]; \
	mov	r0, #0; \
	mvn	r0, r0; \
	bx	lr; \
	END(x)

#else /* GBA */

#define	ENTRY(x) \
	.text; \
	.align	2; \
	.globl	x; \
	.type	x, %function; \
	.arm; \
x:

#define	END(x) \
	.pool; \
	.thumb; \
	.size	x, . - x

/*
 * "mov lr, pc; bx r12" is how this port fakes a syscall trap on hardware
 * with no real SVC exception - but unlike a real trap (which leaves the
 * caller's lr untouched), this necessarily clobbers the live lr register
 * to record where to resume after the simulated call. Every syscall
 * wrapper generated by SYS() below (and sigaction.S, which calls this
 * macro directly) ends with a bare "bx lr" expecting lr to still hold
 * its OWN caller's return address - so without saving/restoring it here,
 * that final "bx lr" jumps back into this wrapper's own post-syscall
 * tail instead of back out to whoever called it, an infinite loop.
 */
#define CALL_SIMSYS(sys_no) \
	push	{lr}; \
	ldr	r12, =SYSCALL_VECTOR_ADDR; \
	ldr	r12, [r12]; \
	mov	lr, pc; \
	bx	r12; \
	.word	sys_no; \
	pop	{lr}

#define SYS(x) \
	ENTRY(x); \
	CALL_SIMSYS(SYS_##x); \
	bcc	2f; \
	ldr	r1, =errno; \
        str	r0, [r1]; \
        mov	r0, #0; \
        mvn	r0, r0; \
2:	bx	lr; \
	END(x)

#endif
