#
# Makefile for DiscoBSD/gba
#
# DEBUG is set to -g by config if debugging is requested (config -g).
#

# sources are located via $S relative to the compilation directory
S=		../../../..

_mach?=		gba
_arch?=		arm
_machdir?=	$S/arch/${_mach}
_archdir?=	$S/arch/${_arch}
_confdir?=	${_machdir}/conf

include		${_confdir}/compiler.mk

INCLUDES=	-nostdinc -I. -I$S -I$S/arch -I${_archdir}/include
DEPFLAGS=	-MT $@ -MP -MD -MF .deps/$*.dep
DEFS=		${INCLUDES} ${PARAM} -DKERNEL ${DEPFLAGS}
CWARNFLAGS=	-Wall

CMACHCPU=	-mcpu=arm7tdmi -march=armv4t -little-endian -mfloat-abi=soft
CMACHFLAGS=	-mthumb -mabi=aapcs -mthumb-interwork
CMACHFLAGS+=	-ffreestanding -fno-builtin -fcommon
CMACHFLAGS+=	${CMACHCPU}

COPTS?=		#-O
CFLAGS=		${DEBUG} ${CWARNFLAGS} ${CMACHFLAGS} ${COPTS}
AFLAGS=		-x assembler-with-cpp ${CWARNFLAGS} ${CMACHFLAGS}
LDFLAGS=	-T ${_confdir}/${LDSCRIPT}
LDFLAGS+=	-nostdlib -Map=$@.map -z noexecstack
LDFLAGS+=	-static -marmelf
LDADD=		-L/usr/lib/gcc/arm-none-eabi/12.2.1/thumb/nofp -lgcc
FIXBIN=		/mnt/c/msys64/usr/local/bin/gbafix.exe

# compile rules: rules are named COMPILE_${SUFFIX}
# SUFFIX is the file suffix, capitalized (e.g. C for a .c file).

COMPILE_C=	${CC} ${CFLAGS} ${DEFS} -c $<
COMPILE_S=	${AS} ${AFLAGS} ${DEFS} -c $<

%OBJS

%CFILES

# load lines for config "xxx" will be emitted as:
# xxx: ${SYSTEM_DEP} swapxxx.o
#	${SYSTEM_LD_HEAD}
#	${SYSTEM_LD} swapxxx.o
#	${SYSTEM_LD_TAIL}
SYSTEM_OBJ=	locore0.o locore.o ${OBJS} ioconf.o
SYSTEM_OBJ+=	sdcard.o
SYSTEM_DEP=	Makefile ioconf.c machine sys .deps ${SYSTEM_OBJ}
SYSTEM_LD_HEAD=	sh $S/conf/newvers.sh > vers.c; ${CC} ${CFLAGS} -c vers.c; rm -f $@
SYSTEM_LD=	-@echo ${LD} ${LDFLAGS} '$${SYSTEM_OBJ}' vers.o -o $@ ${LDADD}; \
		${LD} ${LDFLAGS} ${SYSTEM_OBJ} vers.o -o $@ ${LDADD}
SYSTEM_LD_TAIL=	${SIZE} $@; cp $@ $@.elf; \
		${OBJCOPY} -O ihex $@ $@.hex; \
		${OBJCOPY} -O binary $@ $@.bin; \
		${FIXBIN} $@.bin; \
		${OBJDUMP} -d -S $@ > $@.dis

%LOAD

clean:
	rm -rf .deps unix *.elf *.o *.map *.dis *.bin *.sav *.hex machine sys

clean-all: clean
	rm -f *.h ioconf.c swap*.c vers.c

reconfig ioconf.c: Config $S/../tools/bin/config
	$S/../tools/bin/config Config
	${MAKE} clean

machine:
	ln -s ${_machdir}/include $@

sys:
	ln -s $S/sys $@

.deps:
	mkdir .deps

locore.o: ${_machdir}/${_mach}/locore.S
	${COMPILE_S}

locore0.o: ${_machdir}/${_mach}/locore0.S
	${COMPILE_S}

ioconf.o: ioconf.c
	${COMPILE_C}

# ED_ENABLED (GBAED) reads its root filesystem from the real SD card
# at runtime (ed.c/sd.c), never from this ROM-embedded copy - that
# path is mrams.c-only (MR_ENABLED, plain GBA/mGBA). The mrams build
# embeds the BARE root filesystem (dev/rootfs.img) so its ROM is
# self-contained; ED_ENABLED links a tiny placeholder instead.
ifneq (,$(findstring -DED_ENABLED,$(PARAM)))
SDCARD_IMG=	${_machdir}/dev/sdcard_ed_placeholder.img
else
SDCARD_IMG=	${_machdir}/dev/rootfs.img
# dev/rootfs.img is a .gitignored build artifact: the top-level `make fs`
# builds distrib/gba/rootfs.img from the installed tree and copies it here,
# then relinks. Seed a 1K placeholder if it is missing so a first kernel
# link (before any `make fs`) still succeeds; `make fs` overwrites it with
# the real filesystem afterwards. mrams build only (GBAED has its placeholder).
${_machdir}/dev/rootfs.img:
	dd if=/dev/zero of=$@ bs=1024 count=1 2>/dev/null
endif
sdcard.o: ${SDCARD_IMG}
	${OBJCOPY} -I binary -O elf32-littlearm -B ${_arch} \
	--rename-section .data=.fs_image \
	$< $@

%RULES

-include .deps/*.dep
