#!/usr/bin/env python3
"""
bdf2c.py - convert a BDF bitmap font back into the GBA console font C array
(sys/arch/gba/dev/gba_font.c): 256 glyphs x 8 bytes, one 8-pixel row per byte,
bit 7 = leftmost pixel.

The GBA console renderer (gba_text.c) draws the top GTXT_CHAR_W columns of
each row, so for the 6-wide console keep every glyph <= 6 px wide (5px glyph +
1px gap is the convention); columns 7..6 (the low 2 bits) are ignored. Glyphs
are left-aligned into the byte (column 0 -> bit 7), honoring the BDF BBX
x-offset. Rows are placed into an 8-tall cell using the BBX y-offset relative
to FONT_ASCENT so the baseline matches.

Missing encodings are emitted blank. Encodings >255 or <0 are ignored.

Usage: bdf2c.py font6x8.bdf > gba_font.c
"""
import sys, re

def main():
    lines = open(sys.argv[1]).read().splitlines()
    glyphs = {}                      # encoding -> list[8] of bytes
    ascent = 8                       # rows above the baseline (cell is 8 tall)
    i = 0
    cur = None
    while i < len(lines):
        t = lines[i].split()
        if not t:
            i += 1; continue
        k = t[0]
        if k == "FONT_ASCENT":
            ascent = int(t[1])
        elif k == "ENCODING":
            cur = {"enc": int(t[1])}
        elif k == "BBX":
            cur["bbw"], cur["bbh"], cur["bbxoff"], cur["bbyoff"] = map(int, t[1:5])
        elif k == "BITMAP":
            rows = []
            i += 1
            while lines[i].strip().upper() != "ENDCHAR":
                rows.append(lines[i].strip())
                i += 1
            cur["rows"] = rows
            place(glyphs, cur, ascent)
        i += 1

    emit(glyphs)

def place(glyphs, g, ascent):
    enc = g["enc"]
    if enc < 0 or enc > 255:
        return
    cell = [0]*8
    bbw, bbh = g["bbw"], g["bbh"]
    xoff, yoff = g["bbxoff"], g["bbyoff"]
    nbytes = (bbw + 7)//8
    # BDF places the glyph bbyoff rows above the baseline; the cell top is
    # `ascent` rows above the baseline, so the glyph's top row within the
    # 8-tall cell is ascent - bbh - bbyoff.
    top = ascent - bbh - yoff
    for r, hexrow in enumerate(g["rows"]):
        val = int(hexrow, 16) if hexrow else 0
        # left byte holds the leftmost pixels, MSB-left; normalize to a
        # single left-aligned byte (glyphs are <= 8 wide here).
        if nbytes > 1:
            val >>= (nbytes-1)*8     # keep the top byte (leftmost 8 px)
        val &= 0xFF
        # apply x-offset (shift right into the cell), clamp to 8 px
        byte = (val >> xoff) & 0xFF if xoff >= 0 else (val << (-xoff)) & 0xFF
        cy = top + r
        if 0 <= cy < 8:
            cell[cy] |= byte
    glyphs[enc] = cell

def emit(glyphs):
    out = sys.stdout.write
    out("/*\n")
    out(" * 6x8 1bpp bitmap console font (256 glyphs), 8 bytes/glyph, one\n")
    out(" * 8-pixel row per byte, bit 7 = leftmost pixel. The GBA console\n")
    out(" * (gba_text.c) draws the top 6 columns. Generated by tools/font/\n")
    out(" * bdf2c.py from a BDF; edit the BDF, not this file.\n")
    out(" */\n")
    out("const unsigned char gtxt_font[2048] = {\n")
    for c in range(256):
        cell = glyphs.get(c, [0]*8)
        row = ", ".join("0x%02X" % b for b in cell)
        out("    /* %03d */   %s,\n" % (c, row))
    out("};\n")

if __name__ == "__main__":
    main()
